# Generated by Django 4.1.5 on 2023-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_num', models.CharField(max_length=20)),
                ('start_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SickDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('workers', models.ManyToManyField(blank=True, related_name='sick_dates', to='workers.worker')),
            ],
        ),
        migrations.CreateModel(
            name='OffDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('workers', models.ManyToManyField(blank=True, related_name='off_dates', to='workers.worker')),
            ],
        ),
    ]
