# Generated by Django 4.1.5 on 2023-01-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_num', models.CharField(max_length=20)),
                ('off_dates', models.ManyToManyField(related_name='off_dates', to='workers.date')),
                ('sick_dates', models.ManyToManyField(related_name='sick_dates', to='workers.date')),
                ('start_date', models.ManyToManyField(related_name='start_date', to='workers.date')),
            ],
        ),
    ]
