# Generated by Django 4.1.5 on 2023-02-25 00:14

import django.core.validators
from django.db import migrations, models
import workers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SickDate',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, validators=[workers.models.validate_id_length, workers.models.validate_id_is_a_number])),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_num', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number is invalid', regex='^\\+?\\d{1,4}?[-.\\s]?\\(?\\d{1,3}?\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$')])),
                ('start_date', models.DateField(null=True)),
                ('off_dates', models.ManyToManyField(blank=True, related_name='workers', to='workers.offdate')),
                ('sick_dates', models.ManyToManyField(blank=True, related_name='workers', to='workers.sickdate')),
            ],
        ),
    ]
